import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1a1a1a",
  },
  headerSection: {
    flexDirection: "row",
    padding: 20,
    paddingTop: 10,
  },
  thumbnailContainer: {
    marginRight: 15,
  },
  thumbnail: {
    width: 120,
    height: 160,
    borderRadius: 0,
    backgroundColor: "#333333",
  },
  basicInfo: {
    flex: 1,
    justifyContent: "flex-start",
  },
  title: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 12,
    lineHeight: 24,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "600",
  },
  scoreBadge: {
    backgroundColor: "#2a2a2a",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#444444",
    flexDirection: "row",
    alignItems: "center",
  },
  scoreText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "600",
  },
  description: {
    color: "#cccccc",
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 12,
  },
  expandButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  expandButtonText: {
    color: "#007bff",
    fontSize: 14,
    fontWeight: "600",
    marginRight: 5,
  },
  expandableSection: {
    overflow: "hidden",
  },
  fullDetails: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  sectionTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
  },
  descriptionContainer: {
    marginBottom: 20,
  },
  fullDescription: {
    color: "#cccccc",
    fontSize: 14,
    lineHeight: 20,
  },
  genresContainer: {
    marginBottom: 20,
  },
  genresRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  genreTag: {
    backgroundColor: "#007bff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  genreText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "600",
  },
  additionalInfo: {
    marginBottom: 20,
  },
  infoRow: {
    flexDirection: "row",
    marginBottom: 6,
  },
  infoLabel: {
    color: "#888888",
    fontSize: 13,
    width: 80,
  },
  infoValue: {
    color: "#ffffff",
    fontSize: 13,
    flex: 1,
  },
  statsContainer: {
    marginBottom: 20,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  statItem: {
    alignItems: "center",
    minWidth: 80,
  },
  statNumber: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
  statLabel: {
    color: "#888888",
    fontSize: 11,
    textAlign: "center",
    marginTop: 4,
  },
  episodesSection: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  episodesHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  episodesTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 8,
  },
  episodesTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
  },
  downloadAllButton: {
    backgroundColor: "#28a745",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  downloadAllText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  episodesList: {
    paddingHorizontal: 0,
  },
  episodeRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1e1e1e",
    borderBottomWidth: 1,
    borderBottomColor: "#2a2a2a",
    paddingVertical: 8,
    paddingHorizontal: 16,
    minHeight: 72,
  },
  episodeRowThumb: {
    width: 120,
    height: 68,
    borderRadius: 0,
    backgroundColor: "#2a2a2a",
    overflow: "hidden",
    marginRight: 12,
  },
  episodeRowThumbImg: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  episodeRowThumbPlaceholder: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  episodeRowDownloadedBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "#28a745",
    borderRadius: 8,
    padding: 2,
  },
  episodeRowLoadingBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "#ffc107",
    borderRadius: 8,
    padding: 2,
  },
  episodeRowInfo: {
    flex: 1,
    justifyContent: "center",
  },
  episodeRowTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  episodeRowStatus: {
    color: "#007bff",
    fontSize: 12,
    marginTop: 2,
  },
  episodeRowNotes: {
    color: "#888888",
    fontSize: 11,
    marginTop: 2,
  },
  episodeRowMenu: {
    padding: 8,
  },
  offlineBanner: {
    backgroundColor: "#4a5568",
    padding: 8,
    marginBottom: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#718096",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  offlineBannerText: {
    color: "#ffffff",
    fontSize: 12,
    textAlign: "center",
    fontWeight: "600",
  },
  footer: {
    height: 30,
  },
  skeletonThumbnail: {
    width: 120,
    height: 160,
    borderRadius: 0,
    backgroundColor: "#333333",
    opacity: 0.6,
  },
  skeletonTitle: {
    height: 24,
    backgroundColor: "#333333",
    borderRadius: 4,
    marginBottom: 12,
    opacity: 0.4,
  },
  skeletonStatusRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  skeletonBadge: {
    height: 20,
    width: 60,
    backgroundColor: "#333333",
    borderRadius: 12,
    opacity: 0.3,
  },
  skeletonDescription: {
    height: 16,
    backgroundColor: "#333333",
    borderRadius: 4,
    marginBottom: 6,
    opacity: 0.3,
  },
  skeletonDescriptionShort: {
    height: 16,
    width: "70%",
    backgroundColor: "#333333",
    borderRadius: 4,
    marginBottom: 12,
    opacity: 0.3,
  },
  skeletonButton: {
    height: 20,
    width: 80,
    backgroundColor: "#333333",
    borderRadius: 4,
    opacity: 0.3,
  },
  skeletonIcon: {
    width: 18,
    height: 18,
    backgroundColor: "#333333",
    borderRadius: 4,
    opacity: 0.3,
  },
  skeletonEpisodesTitle: {
    height: 18,
    width: 150,
    backgroundColor: "#333333",
    borderRadius: 4,
    opacity: 0.3,
  },
  skeletonDownloadButton: {
    height: 32,
    width: 70,
    backgroundColor: "#333333",
    borderRadius: 8,
    opacity: 0.3,
  },
  skeletonEpisodeItem: {
    flex: 1,
    backgroundColor: "#333333",
    borderRadius: 4,
    opacity: 0.4,
  },
  skeletonEpisodeText: {
    height: 14,
    width: 60,
    backgroundColor: "#333333",
    borderRadius: 4,
    opacity: 0.4,
  },

  // ── Lista de episodios sin miniatura ─────────────────────────────────────
  // Un estado, una señal: visto = opaco, descargado = barra verde,
  // actual = número en azul.
  epRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 11,
    paddingRight: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#222222",
  },
  epRail: {
    width: 3,
    alignSelf: "stretch",
    borderRadius: 2,
    backgroundColor: "#333333",
  },
  epRailDownloaded: {
    backgroundColor: "#22c55e",
  },
  epNumber: {
    fontFamily: "monospace",
    fontSize: 13,
    color: "#888888",
    minWidth: 34,
    textAlign: "right",
  },
  epNumberCurrent: {
    color: "#007bff",
    fontWeight: "700",
  },
  epBody: { flex: 1 },
  epTitle: { color: "#e8e8e8", fontSize: 14.5 },
  // "Visto" se comunica SOLO con opacidad, sin etiqueta.
  epDim: { color: "#5f6470" },
  epStatus: { color: "#888888", fontSize: 12, marginTop: 3 },
  epMenu: { padding: 6 },

  // ── Tarjeta "Continuar" ──────────────────────────────────────────────────
  resumeCard: {
    backgroundColor: "#2a2a2a",
    borderWidth: 1,
    borderColor: "#383838",
    borderRadius: 10,
    padding: 12,
    marginBottom: 14,
  },
  resumeLabel: {
    color: "#007bff",
    fontSize: 10.5,
    fontWeight: "700",
    letterSpacing: 1,
  },
  resumeEpisode: { color: "#ffffff", fontSize: 16, marginTop: 5 },
  resumeBar: {
    height: 3,
    backgroundColor: "#333333",
    borderRadius: 2,
    marginTop: 9,
    overflow: "hidden",
  },
  resumeBarFill: { height: "100%", backgroundColor: "#007bff" },

  // ── Chips de rango (solo series de más de 50 episodios) ──────────────────
  rangeBar: { gap: 6, paddingBottom: 10 },
  rangeChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#383838",
    backgroundColor: "#2a2a2a",
  },
  rangeChipActive: { backgroundColor: "#007bff", borderColor: "#007bff" },
  rangeChipText: { color: "#cccccc", fontSize: 11.5, fontFamily: "monospace" },
  rangeChipTextActive: { color: "#ffffff", fontWeight: "700" },
});
